### PR TITLE
Allows to specify target of a DelayedTask on command line.

### PR DESCRIPTION
**Pull request by felixfontein**
First shot at implementing #20: allowing to specify targets and delayed tasks of ```DelayedTask```'s on the command line.

This is based on doit 0.27.0, to be able to test it with Nikola's earlytask_impl branch (see https://github.com/getnikola/nikola/pull/1632).

### CODE REVIEW

**Comment by felixfontein** [comment]
(Sorry it took that long... There were too many other things happening :) )

**Comment by schettino72** [comment]
Hi, thanks for working on this.

I would like to know more about your concrete use-case. For which targets in Nikola you would use this. I am asking this because I am thinking that attaching regexp to identify which targets a task creates might be a better solution.

regexp advantages:
  - result is always correct, even on first run because a task_dep will be executed
  - no need to load DelayedTasks that wont be used
  - cleaner implementation

regexp disavantages:
  - It might not be possible unambiguosly describe task targets by a regexp

I guess that in real life a regexp should be suitable, so lets check your use-case with Nikola :)

Also related to this is #30 (but about basename instead of target)

**Comment by felixfontein** [comment]
Well, there are two main reasons I'd like this feature:

 - More meta: to make nikola's earlytask_impl branch more compatible with current behavior;

 - More conrete: I want to be able to tell nikola to build specific targets, which isn't possible in the earlytask_impl branch as all tasks (which specify the targets) are created by delayed task loaders.

I also don't think this collides with regexps, as there's always the choice to choose ".*" as a regexp describing the generated tasks' targets. (And for some tasks, it might not even be possible to specify something more concrete.)

I think regexp support would be nice to have (as task generators which can specify quite clearly which targets they generate don't have to be loaded), but especially for backwards compatbility with older plugins (or in some cases, when it is not possible to say anything more concrete about targets except that they are in ```output/```, for example) this won't help much.

**Comment by schettino72** [comment]
I agree this feature is useful, what I am saying is that regexp is superior in many aspects and its limitations are not very relevant in practice. I forgot to mention another big regexp disavantage: you need to werite the regexp!

For my own Nikola based blog, I guess it would not be hard to make a regexp for each target.
 - indexes: "/output/index(.*).html"
 - posts: "/output/posts/(.*).html"
 - categories: "/output/categories/(.*).html"
 - archives: "/output/(\d\d\d\d)/(.*).html"

Yes it would affect backward compatibility with plugins but this is also not coming for free...
What makes me unconfortable with this change is that doit might do the right thing *or not* depending on the state of previous runs. It is very bad for  build-tool when people stop trusting it.

**Comment by schettino72** [comment]
I just implemented https://github.com/pydoit/doit/commit/03f0cf7e1b4b6915c35619ceab367bdda77e8efd to allow specifying a **sub-task** from a DelayedTask. It is almost the same as what it would take to implement specifying **targets** (but a bit easier). 

The patch itself made it even more clear to me that use of regexp is the right way to go.
I am sorry if you feel that I mislead you to implement a patch that I wont accept, sometime it is hard to 
 make a call before actually looking at an implementation. Sorry my mistake.

**Comment by felixfontein** [comment]
I still don't see what you want to do in case you find two regexs matching a target, or if a delayed task creates a task which name it didn't announce before. Or is that not allowed? (Which would be ways to strict, from my point of view.)

**Comment by schettino72** [comment]
@felixfontein please check if this branch is good enough for you: https://github.com/pydoit/doit/compare/delayed-target-regex?expand=1

Announcing a name is optional. There is no support for 2 regex matching a target (but could be added).

**Comment by felixfontein** [comment]
I don't think it is always possible to avoid having not two regexps matching the same target. At least, not with an extreme amount of PITA and (even worse) user interaction. In particular for Nikola, I don't want to force end-users to start writing regexps, and I neither want to reduce Nikola's flexibility of allowing to put things where you want them. So I'm still convinced that the code I wrote (or something else doing something similiar) is needed.

**Comment by schettino72** [comment]
The code could be improved to handle more than one matching regexps.

As I said before the problem with your code is that it doesnt work if the targets intermediates were never built. IMO that would make doit not *trustable* ... Any other idea ?

**Comment by felixfontein** [comment]
But how is that different from when you specify a delayed task on the command line, where the targets also have dependencies which are produced by some other delayed task? What does doit currently do in that situation?

**Pull request closed without merging**
