### PR TITLE
Outputting an error message if no delayed-loaded task built target.

### PR DESCRIPTION
**Pull request by felixfontein**
Addressing second part of #60.

### CODE REVIEW

**Comment by schettino72** [comment]
I was thinking about implementing it in a different way. I would check if any task from a delayed creator has the target right after the task is created. It is more complicated to implemented than what you did but has 2 advantages:

 - you could give a more detailed error message mentioning which delayed creators might create that task.
 - you could cancel the loading/creation of other tasks right after finding the task that creates the specified target.

**Comment by felixfontein** [comment]
What do you mean by more detailed error message? Do you want it to include a list of delayed tasks for which the regex matched? That can easily be added by turning `targets_to_search_for` into a dict, mapping a target to a list of task names which generate it. (The newest commit now does this.)

**Comment by felixfontein** [comment]
The second point you mentioned seems interesting; in fact, I'm hoping that it might help to fix the built-too-much problem mentioned in #60. But I don't see how it helps with the error message.

**Comment by felixfontein** [comment]
Actually, here's a try of mine to implement point 2: https://github.com/felixfontein/doit/commit/4c8cefe2f8ec588a5257d3f3c02b955b9c6911c9
It doesn't help with the problem mentioned in #60, though.

**Comment by schettino72** [comment]
@felixfontein check this patch https://github.com/pydoit/doit/commit/d6d457e2e580501ea3517bae9cbac049f5afba48

**Comment by schettino72** [comment]
I guess we can forget my comment about better error messages. I guess error messages is more important with typos... and in that case it would be better to have a very simple error message.

**Comment by felixfontein** [comment]
Your patch (after removing `set()`) also doesn't help with the problem mentioned in #60, but it looks nicer :)

**Comment by schettino72** [comment]
it fixes #60 for me. are you sure you didnt modify the example? can you post the output you get?

**Comment by felixfontein** [comment]
Ok, I did some more tests. It works *sometimes* for me, and sometimes not. Maybe half of the times, it builds all `.out` files, and half of the times only `c.out`.

If it builds everything, I get:
```
$ doit run c.out
.  early
.  build:b.in
.  build:c.in
.  build:a.in
```

**Comment by schettino72** [comment]
I updated my branch. needed to use OrderedDict...

But note how it depends on the order the tasks were defined. If you define `task_final` before `task_build` it wont work.

TODO:

 - [ ] tests
 - [ ] error message if target not found

**Comment by felixfontein** [comment]
How do you want the error message be implemented? I don't really see how to do it much differently than in https://github.com/felixfontein/doit/commit/a2a40992aa27245458d9dbc929ee2bace2995944.

**Comment by schettino72** [comment]
I guess same message as when not using DelayedTask should be ok.

**Comment by felixfontein** [comment]
My question was more at how outputting the error should be implementing. Is adding a `post_run()` function fine as in this original PR?

**Comment by schettino72** [comment]
> My question was more at how outputting the error should be implementing. Is adding a post_run() function fine as in this original PR?

I would need to implement it to decide :) I would like to avoid having a `post_run()`... But not sure how complicated would be to modify the `RegexGroup` class to track all tasks and targets created.

When all tasks from a RegexGroup have already been created we can check if the targets it is expected to create is on any task, right?

**Comment by felixfontein** [comment]
See #70 for a try to implement that.

**Pull request closed without merging**
