### PR TITLE
Fix pickling on windows so that we can spawn new processes

### PR DESCRIPTION
**Pull request by gstorer**
Fix for #50. 

Note that I elected to skip pickling all of dep_manager. I figure that its likely extra non-picklable things could be added here in the future.

### CODE REVIEW

**Comment by schettino72** [comment]
thanks.

- please add unittests, checking that `Runner` object pickle should be good enough.
- add your name on authors file

**Comment by schettino72** [comment]
is this patch really enough? python docs says that  `Process.__init__` `target` can not be a method. But you did not modify that.

**Comment by gstorer** [comment]
It would appear to be enough. 

The docs say everything has to be picklable. I think, from my brief eduction on the subject over the last few of days, that the example given is a simplification. Because ```Runner``` is picklable and the method is specified 'normally' everything is ok.

I'll add some tests in the next day or so.

**Comment by gstorer** [comment]
I've had a closer look at some of the existing unit tests. I'd say you pretty much already have coverage for this if the tests are run on Windows. I'll add an explicit pickle one for quick testing on other platforms.

A bigger problem is the non picklable nature of anonymous code. E.g. all the function defined within methods. A lot of tests are failing on Windows because the tests feed these functions in as arguments. 

Would it be better to try and blank all the user specifiable functions (assuming this won't break things further) or change the unit tests not to use them?

The offending functions in test_runner.py (I'm sure there's heaps elsewhere):
https://github.com/pydoit/doit/blob/master/doit/tests/test_runner.py#L337
https://github.com/pydoit/doit/blob/master/doit/tests/test_runner.py#L477
https://github.com/pydoit/doit/blob/master/doit/tests/test_runner.py#L494
https://github.com/pydoit/doit/blob/master/doit/tests/test_runner.py#L602
https://github.com/pydoit/doit/blob/master/doit/tests/test_runner.py#L684
https://github.com/pydoit/doit/blob/master/doit/tests/test_runner.py#L693

**Comment by schettino72** [comment]
> The docs say everything has to be picklable

Which python version are you using? Actually the docs passage I was referring to is only present in python2 docs... maybe this limitation was fixed in python3.


>  I'd say you pretty much already have coverage for this if the tests are run on Windows. I'll add an explicit pickle one for quick testing on other platforms.

Yes. That's the idea, the functionality is already being tested. But we can exercise the code while testing in all platforms.


> A lot of tests are failing on Windows because the tests feed these functions in as arguments.

If we are serious about having Windows as development platform a CI is required.

**Comment by schettino72** [comment]
> Would it be better to try and blank all the user specifiable functions (assuming this won't break things further) or change the unit tests not to use them?

The code already balnks as much as possible (if not let me know the specific case). So we need to fix the tests.

**Comment by gstorer** [comment]
We're using 2.7 here and it seems to work ok. Perhaps the limitation was removed earlier and the docs didn't get updated.

I fixed the links to the breaking functions that I've found in the tests.

For full Windows support it does indeed seem as though some CI is needed. I'm still hoping someone else will volunteer there though...

**Comment by joschkazj** [comment]
Thanks for looking into this.
I've tried the changes locally on Windows and can confirm the issue with the nested functions:

> A bigger problem is the non picklable nature of anonymous code. E.g. all the function defined within methods. A lot of tests are failing on Windows because the tests feed these functions in as arguments.

Additionally the test [TestMRunner_parallel_run_tasks.test_task_not_picklabe_multiprocess](https://github.com/pydoit/doit/blob/master/tests/test_runner.py#L683) (BTW: shouldn't it be called ...picklab**l**e?) fails for me. This can be fixed by catching the PicklingError in [MRunner.run_tasks()](https://github.com/pydoit/doit/blob/master/doit/runner.py#L417) as follows:
```
diff -r 8602954e6098 doit/runner.py
--- a/doit/runner.py	Mon May 25 15:29:35 2015 +0800
+++ b/doit/runner.py	Fri May 29 11:16:40 2015 +0200
@@ -418,7 +418,10 @@
         # task queue - tasks ready to be dispatched to sub-processes
         job_q = self.Queue()
         self._run_tasks_init(task_dispatcher)
-        proc_list = self._run_start_processes(job_q, result_q)
+        try:
+            proc_list = self._run_start_processes(job_q, result_q)
+        except pickle.PicklingError as exc:
+            raise InvalidTask(repr(exc))
 
         # wait for all processes terminate
         proc_count = len(proc_list)
```

**Comment by schettino72** [comment]
I created a #56, hopefully after that is implemented I will be able to land all the fixes. I am a bit lost at the moment... Your effort won't be wasted, please just have a bit of patience.

**Comment by schettino72** [comment]
@gstorer we finally got a CI running: https://ci.appveyor.com/project/schettino72/doit

I don't how to trigger it for an old pull-request. Can you update your branch to latest master and push? 
(I am hoping appveyor also runs on PRs) After that I will review your patch. Thanks.

**Comment by schettino72** [comment]
So I have another WIP branch https://github.com/pydoit/doit/compare/test

My branch modifies how to pickle MRunner objects only:
 - it excludes the whole TaskDispatcher object, so no need to modify how TaskDispatcher is pickled
 - it also excludes the reporter object, than it pass a reference just the reporter class when using multi-processing.

There is a big problem of test getting stuck on python2.7 (https://ci.appveyor.com/project/schettino72/doit/build/job/gsqqqe94ih2hocms) no idea why.

There is still other failing tests but I suspect they are issues with the tests itself...

I am closing this pull-request, my `test` branch is the way forward. Discussion is going back to original issue #50

**Pull request closed without merging**
