### PR TITLE
Fix #349: not able to pass task args in single task execution

### LINKED ISSUE #349: Cannot pass task arguments when --single is used
**Describe the bug**

> Please include a minimal `dodo.py` that reproduces the problem.
> If relevant also include the command line used to invoke ``doit``.

Cannot pass task arguments when `--single` is used.

### `dodo.py`

```python
import time

def task_long_running():
    def sleep_3():
        time.sleep(3)
    return {'actions': [(sleep_3,)]}

def task_params():
    def show_params(param1):
        print("PARAM:", param1)
    return {'actions': [(show_params,)],
            'params': [{'name': 'param1',
                        'short': 'p',
                        'default': 'default value'},],
            'verbosity': 2,
            'task_dep': ['long_running']
            }
```

### Expected behavior
```shell
$ doit params -p val
.  long_running
.  params
PARAM: val
$ doit -s params -p val
.  params
PARAM: val
$
```

### Actual behavior
```shell
$ doit params -p val
.  long_running
.  params
PARAM: val
$ doit -s params -p val
Traceback (most recent call last):
  File "/lib/python3.7/site-packages/doit/doit_cmd.py", line 190, in run
    return command.parse_execute(args)
  File "/lib/python3.7/site-packages/doit/cmd_base.py", line 150, in parse_execute
    return self.execute(params, args)
  File "/lib/python3.7/site-packages/doit/cmd_base.py", line 601, in execute
    return self._execute(**exec_params)
  File "/lib/python3.7/site-packages/doit/cmd_run.py", line 212, in _execute
    task = self.control.tasks[task_name]
KeyError: '-p'
$
```

**Environment**
1. OS: macOS Catalina 10.15.2
2. python version: Python 3.7.6
3. doit version: 
```
0.32.0
lib @ /lib/python3.7/site-packages/doit
```

### PR DESCRIPTION
**Pull request by davidzyx**
Fixes #349

### CODE REVIEW

**Comment by schettino72** [comment]
thanks. Can you add a unit-test?

**Comment by davidzyx** [comment]
> thanks. Can you add a unit-test?

Sure. I'll see what I can do

**Comment by davidzyx** [comment]
@schettino72 done

**Comment by schettino72** [comment]
merged. thanks

**Pull request closed without merging**
