### PR TITLE
Utility for %doit IPython magic function.

### PR DESCRIPTION
**Pull request by ankostis**
Inspired from the promoted (software-carpentry's lesson)[http://www.software-carpentry.org/v5/intermediate/doit/01-doit_basics.html] i crafted a really small but usable utility function that registers a ``%doit`` magic function in IPython interactive shells.

### CODE REVIEW

**Comment by schettino72** [comment]
Thanks for taking the time to contribute!

* I guess better put this into `tools.py`, as this code is useful to users but not used by doit itself.
* Any chance of writing a unit-test for this?
* Documentation looks good, please also add link to IPython docs about this magic functions.
* Add your name to the `AUTHORS` file.

**Comment by ankostis** [comment]
Will do your suggestion.
You want me to rebase-squash commits in the end (but loose comments)?

**Comment by schettino72** [comment]
I prefer you leave it as is and I rebase-squash myself when merging. 
You never know when my reviews will finish :D 

I forgot a few things:

* move the docs to the `tools` page also
* add an entry on CHANGES file
* there is a doit task *spell* to spell check the docs, it is annoying that it doesnt recognize code. So whatever it complains and it is not a typo needs to be added to `doc/dictionary.txt`

**Comment by ankostis** [comment]
@schettino72  wrote:
> Any chance of writing a unit-test for this?

This is tough.
- Embedding might help: https://ipython.org/ipython-doc/dev/interactive/reference.html#embedding
- Or doctests: https://github.com/ipython/ipython/wiki/Dev:-Testing

**Comment by schettino72** [comment]
thanks. this is now merged !

* I found a way to explicitly import `get_ipython`
* I removed some duplicated docs from code since it already shows up in user docs
* Also did some minor docs reformatting to 80 columns and white-space removal

**Pull request closed without merging**
