### PR TITLE
Display dependenciess-graph using networkx & matplotlib

### LINKED ISSUE #26: View Dependencies as a Tree
This issue was first raised in this [discussion](https://groups.google.com/forum/#!topic/python-doit/oWs_VRCHHmE)

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8853903-view-dependencies-as-a-tree?utm_campaign=plugin&utm_content=tracker%2F1885485&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1885485&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ankostis**
doit_dependencies_graph
FIX #26: Updated ``doit list`` cmd with `--graph` option that opens a matplotlib node-graph window.

Notes:
- It could print a more civilized error if `matplotlib` not installed.
- The `networkx` has been added in the install-requirements; it is a pure-python library for both py2 and py3 so no problems expected from users.
- Tests, CHANGES,and doc-updates if eventually gets accepted.

### CODE REVIEW

**Comment by schettino72** [comment]
I am closing this... Looking for it to be created on its own repository.

**Comment by ankostis** [comment]
I would appreciate if you took the time and created a skeleton for the new plugin-project.

**Comment by schettino72** [comment]
Create here: https://github.com/pydoit/doit-graphx

Should be good enough to get started.

**Comment by ankostis** [comment]
Yes, that is fine, thanks.

**Comment by ankostis** [comment]
Ported functionality as (draft) plugin `graphx` cmd here: https://github.com/pydoit/doit-graphx

**Pull request closed without merging**
