### PR TITLE
 Add support for new-style command formatting.

### PR DESCRIPTION
**Pull request by Janfel**
This PR will make it possible to use Python [Format String Syntax][fsyntax] in `cmd-actions` for implicit keyword substitution and `getargs`.

**This change has a slight chance of breaking existing scripts!**

If an existing `dodo.py` file uses `{}` or `{something}` in a `cmd-action`, chances are, the formatter will throw an error.
Existing old-style-syntax will continue to work as expected.

[fsyntax]:https://docs.python.org/3/library/string.html#format-string-syntax

### CODE REVIEW

**Comment by Janfel** [comment]
Are there tests for the old-style syntax i can copy?

**Comment by schettino72** [comment]
also a bit worried about backward compatibility.
What do you think about adding a config like `DOIT_CONFIG` `new_style_string_formatting` ?

**Comment by Janfel** [comment]
I locked the feature behind the flag `new_style_string_formatting`, as you suggested. I also updated the parts of the documentation that seemed relevant and wrote Unit Tests for the feature being and being not explicitly enabled.

**Comment by schettino72** [comment]
@Janfel thanks, you are so fast... 

Thinking over, I guess it would be better to provide a way to migrate to new style and not force people to forever quote their string to both old and new-style format.

So what you think about having: `action_string_formatting` with possible values of `old` (default), `both`, `new`. Then on future releases we could migrate the default from `old` -> `both` -> `new`.

I guess this would be a very small change from your current patch and provide extra value. what do you think?

By the way, also add your name into  AUTHORS file, and add an entry on CHANGES.

**Comment by Janfel** [comment]
This should be everything.

**Comment by schettino72** [comment]
Hi, I am reviewing it and making some changes... WIP here: https://github.com/pydoit/doit/tree/Janfel-janfel-patch-newstyle-formatting

- the unit-tests are broken on windows. see appveyor... the issue is on different escaping on different shells. Thats a can of worm... i would just ignore escaping on tests
- your tests are very comprehensive but also complex. I usually avoid having and logic (IF, FOR) on tests. Also tests should be specific to formatting. no need to test other related features again.
- the formatting should be global, not per task. That just make the implementation easier then what you have done.
- I still want to review the documentation. it needs to make sense when read in order.

I probably wont have more time this week, so please be patient :grin:

**Comment by schettino72** [comment]
squashed and merged. thanks.

**Pull request closed without merging**
